### ISSUE TITLE
Switchboard Initial Security Tracking Issue

### ISSUE THREAD

**Issue by max-cura** [treadmill-tb/treadmill#13]
Tracking issue for various web-based security issues for the initial version of `switchboard`.

Topic: CSRF
- [ ] Origin/Referer checking in `Subject` extractor
- [X] CSRF mitigation with synchronizer pattern
- [X] Login CSRF mitigation

Topic: XSS
- [ ] Input sanitization (maybe use `ammonia`?)

Topic: Logs
- [ ] Sensitive headers (`tower_http::sensitive_headers`)
- [ ] Prevent logging of sensitive values in switchboard-side code
